### ISSUE TITLE
Missile mass is used wrong

### ISSUE THREAD

**Issue by Xellzul** [FlareFlo/wt_ballistics_calc#1]
Missile should use mass linearly interpolated from 
mass - massEnd for engine_stage 0
massEnd - massEnd1 for engine_stage 1
and massEnd1 if avaible else massEnd for glide

currently only mass is used for burner 
and massEnd for gliding

( runner.rs:127 )

**Comment by FlareFlo** [comment]
How should multi-staged engines be handled, as there is no specific ratio for burner-time to weight ratio?

Edit: I would simply take mass - massEnd and then split it across via timefire0 / timefire1.

**Comment by Xellzul** [comment]
Like Aim7F ?:

"mass": 231.33
"massEnd": 193.68
"massEnd1": 170.1

"timeFire": 4.5
"timeFire1": 11.0

(given no fire delay)
Mass at
**T0: 231.33**
**T1: 222.96** _mass - (((mass - massEnd) / totalBurnTimeForStage) * burnTimeOfStage) - (231.33 - (((231.33 - 193.68) / 4.5) * 1))_
**T4.5: 193.68**
**T10: 182.39** _massEnd- (((massEnd- massEnd1) / totalBurnTimeForStage) * burnTimeOfStage) - 193.68 - (((193.68 - 171.1) / 11) * 5.5)_
**T15.5: 170.1**

**Comment by FlareFlo** [comment]
My bad, I just realized that multi-engine missiles have multiple mass-end parameters, this greatly simplifies the process.

Edit; requires upstream data-extractor patch; https://github.com/Warthunder-Open-Source-Foundation/wt_datamine_extractor/commit/4bf4acd29ae922d77a4e888ed8dc18ecf8571f91

Edit1: Tests have passed, proceeding with integration https://github.com/Warthunder-Open-Source-Foundation/wt_datamine_extractor/runs/5053708583?check_suite_focus=true

**Comment by Xellzul** [comment]
Yea it should be used if available for glide
e.g. here:
`a = (-drag_force / missile.mass_end) - gravity;`

**Comment by FlareFlo** [comment]
New algorithm up for review

Edit: found some bugs, getting them patched right now

**Comment by FlareFlo** [comment]
Fixed follow up error with the calculation of single-stage engines https://github.com/Warthunder-Open-Source-Foundation/wt_ballistics_calc/commit/849af78aff156e125024474202ff5802109d43ff
